# Generated by Django 3.0.6 on 2020-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('classes', '0002_auto_20200919_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(
                related_name='studying_classes', to='authorization.User'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(
                related_name='teaching_classes', to='authorization.User'),
        ),
    ]
