# Generated by Django 3.0.6 on 2020-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_avatar'),
        ('classes', '0005_class_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='studying_classes', to='authorization.User'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_classes', to='authorization.User'),
        ),
    ]
