# Generated by Django 3.0.6 on 2020-09-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0002_user_avatar'),
        ('class_channels', '0002_channel_related_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='written_messages', to='authorization.User')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='messages', to='class_channels.Channel')),
            ],
        ),
    ]
