# Generated by Django 3.0.6 on 2020-09-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_channels', to='authorization.User')),
                ('members', models.ManyToManyField(related_name='channels', to='authorization.User')),
            ],
        ),
    ]
