# Generated by Django 3.0.6 on 2020-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='class',
            name='join_key',
            field=models.SlugField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='class',
            name='key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
